version: '3.8'
services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo_db
    volumes:
      - .:/app
    networks:
      - todo-network

  db:
    image: postgres:15
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - todo-network

volumes:
  db_data:

networks:
  todo-network:
    driver: bridge