// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Task struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Text      sql.NullString `json:"text"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Done      sql.NullBool   `json:"done"`
}
