// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (int64, error)
	DeleteTask(ctx context.Context, id int64) error
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTaskTitles(ctx context.Context, arg GetTaskTitlesParams) ([]GetTaskTitlesRow, error)
	Search(ctx context.Context, plaintoTsquery string) ([]SearchRow, error)
	SetDone(ctx context.Context, arg SetDoneParams) error
	UpdateTaskText(ctx context.Context, arg UpdateTaskTextParams) error
	UpdateTaskTitle(ctx context.Context, arg UpdateTaskTitleParams) error
}

var _ Querier = (*Queries)(nil)
